services:
  nextjs:
    image: ghcr.io/larsniet/lusabaini-nextjs:latest
    environment:
      REVALIDATE_SECRET: ${REVALIDATE_SECRET:-8F526B4245EC7A86446FC715D2BEF}
    ports:
      - "8050:3000"
    restart: always

  sanity:
    image: ghcr.io/larsniet/lusabaini-sanity:latest
    ports:
      - "8051:3333"
    restart: always
